[
  {
    "name": "HRSG1_OPACITY_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT0.0",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL2",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL6",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL10",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL14",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X18.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X18.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL20",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL24",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL28",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL32",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL36",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT40",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT42.0",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL44",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X48.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X48.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X48.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X48.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_OPACITY_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT50",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT52",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL54",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL58",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL62",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL66",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X70.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X70.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL72",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL76",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL80",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL84",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL88",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT92",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT94",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL96",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X100.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X100.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X100.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X100.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_PARTICULATE_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT102",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT104",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL106",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL110",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL114",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL118",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X122.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X122.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL124",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL128",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL132",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL136",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL140",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT144",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT146",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL148",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X152.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X152.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X152.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X152.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_FLOW_GAS_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT154",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT156",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL158",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL162",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL166",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL170",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X174.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X174.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL176",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL180",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL184",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL188",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL192",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT196",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT198",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL200",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X204.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X204.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X204.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X204.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_NOX_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT206",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT208",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL210",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL214",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL218",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL222",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X226.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X226.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL228",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL232",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL236",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL240",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL244",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT248",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT250",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL252",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X256.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X256.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X256.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X256.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_SO2_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT258",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT260",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL262",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL266",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL270",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL274",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X278.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X278.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL280",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL284",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL288",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL292",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL296",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT300",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT302",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL304",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X308.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X308.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X308.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X308.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT310",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT312",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL314",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL318",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL322",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL326",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X330.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X330.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL332",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL336",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL340",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL344",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL348",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT352",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT354",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL356",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X360.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X360.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X360.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X360.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_CO2_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT362",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_CH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT364",
    "description": "Channel Number",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_IN_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL366",
    "description": "Start range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_IN_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL370",
    "description": "End range of input",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_OUT_LO",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL374",
    "description": "Start range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_OUT_HI",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL378",
    "description": "End range of output",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LIM_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X382.0",
    "description": "Limit output with OUT_LO & OUT_HI",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_SIM",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X382.1",
    "description": "Simulation",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_SIM_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL384",
    "description": "Simulatin value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL388",
    "description": "Setpoint of LALL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_L",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL392",
    "description": "Setpoint of LAL",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_H",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL396",
    "description": "Setpoint of LAH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_HH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL400",
    "description": "Setpoint of LAHH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_RET_VAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT404",
    "description": "",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_RAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT406",
    "description": "Raw value",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_OUT",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,REAL408",
    "description": "Scaling result",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LALL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X412.0",
    "description": "Limit alarm LOW LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LAL",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X412.1",
    "description": "Limit alarm LOW",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LAH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X412.2",
    "description": "Limit alarm HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LAHH",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,X412.3",
    "description": "Limit alarm HIGH HIGH",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  },
  {
    "name": "HRSG1_O2_LAW",
    "device": ObjectId("59ca5fcc4419833aa4ffabc0"),
    "address": "DB10,INT414",
    "description": "Limit Alarm Word ( 1 : LALL; 2 : LAL; 3 : LAH; LAHH)",
    "min": "",
    "max": "",
    "lo_lim": "",
    "hi_lim": "",
    "eu": ""
  }
]